package routes

import (
	"net/http"

	// Import the generated docs so swag's init() registers the spec.
	_ "github.com/petervdpas/goop2/docs"

	"github.com/swaggo/swag"
)

// RegisterOpenAPI serves the Swagger 2.0 spec at GET /api/openapi.json.
// The spec is generated by `go generate` (swag init) from // @annotations on
// stub functions in openapi_annotations.go — it always matches the code.
func RegisterOpenAPI(mux *http.ServeMux) {
	handleGet(mux, "/api/openapi.json", func(w http.ResponseWriter, r *http.Request) {
		doc, err := swag.ReadDoc()
		if err != nil {
			http.Error(w, "spec unavailable", http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Cache-Control", "no-cache")
		w.Write([]byte(doc))
	})
}
